name: safecrypt
description: "A secure and easy-to-use encryption tool for Flutter applications. Secure Your Data, Secure Your Life."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  icons_plus: ^5.0.0
  flutter_animated_splash: ^0.0.10
  firebase_database: ^11.2.0
  device_preview: ^1.2.0

  flutter_svg: any
  validators: ^3.0.0
  loading_animation_widget: ^1.3.0
  awesome_dialog: ^3.2.1
  shared_preferences: ^2.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png" # Replace with the path to your app icon
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/icon.png" # Replace with the path to your app icon
  adaptive_icon_background: "#ffffff" # Background color for the icon

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon.png # Ensure this is the correct path to your icon
    - assets/images/bg1.png
    - assets/images/4square.svg
    - assets/images/bell.svg
    - assets/images/codesandbox.svg
    - assets/images/compass.svg
    - assets/images/copy.svg
    - assets/images/creditcard.svg
    - assets/images/profilepic.jpg
    - assets/images/shield.svg

  # You can also include custom fonts here, if needed:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700